import { antipattern, correctness, effectNative, style } from "@effect/tsgo/oxlint-presets";
import { defineConfig } from "oxlint";

export default defineConfig({
  extends: [correctness, antipattern, effectNative, style],
  ignorePatterns: [
    "**/dist/**",
    "**/build/**",
    "**/coverage/**",
    "**/.tsbuildinfo",
    "**/node_modules/**",
    ".agents/**",
    ".dotai/**",
    ".pi/**",
  ],
  options: {
    denyWarnings: true,
    reportUnusedDisableDirectives: "error",
    typeAware: true,
  },
  plugins: [
    "typescript",
    "oxc",
    "import",
    "jsdoc",
    "node",
    "promise",
    "unicorn",
    "vitest",
    "effecttsgo",
  ],
  categories: {
    correctness: "error",
    suspicious: "error",
    pedantic: "error",
    perf: "error",
    nursery: "error",
  },
  rules: {
    "arrow-body-style": "error",
    curly: "error",
    "default-case-last": "error",
    "default-param-last": "error",
    "guard-for-in": "error",
    "logical-assignment-operators": "error",
    "no-console": "error",
    "no-continue": "error",
    "no-duplicate-imports": "error",
    "no-empty": "error",
    "no-empty-function": "error",
    "no-eq-null": "error",
    "no-implicit-coercion": "error",
    "no-labels": "error",
    "no-multi-assign": "error",
    "no-nested-ternary": "error",
    "no-new-func": "error",
    "no-param-reassign": "error",
    "no-plusplus": "error",
    "no-proto": "error",
    "no-return-assign": "error",
    "no-sequences": "error",
    "no-var": "error",
    "object-shorthand": "error",
    "prefer-const": "error",
    "prefer-object-has-own": "error",
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "prefer-template": "error",
    "import/no-amd": "error",
    "import/no-commonjs": "error",
    "import/no-cycle": "error",
    "import/no-duplicates": "error",
    "import/no-dynamic-require": "error",
    "import/no-mutable-exports": "error",
    "import/no-self-import": "error",
    "import/no-webpack-loader-syntax": "error",
    "oxc/no-async-await": "error",
    "oxc/no-const-enum": "error",
    "typescript/consistent-type-assertions": [
      "error",
      {
        assertionStyle: "never",
      },
    ],
    "typescript/consistent-type-definitions": ["error", "type"],
    "typescript/consistent-type-imports": [
      "error",
      {
        prefer: "no-type-imports",
      },
    ],
    "typescript/explicit-module-boundary-types": "error",
    "typescript/no-dynamic-delete": "error",
    "typescript/no-empty-object-type": "error",
    "typescript/no-explicit-any": "error",
    "typescript/no-namespace": "error",
    "typescript/no-non-null-assertion": "error",
    "typescript/no-require-imports": "error",
    "typescript/no-var-requires": "error",
    "typescript/use-unknown-in-catch-callback-variable": "error",
    "unicorn/filename-case": "error",
    "unicorn/no-abusive-eslint-disable": "error",
    "unicorn/no-null": "error",
    "unicorn/no-process-exit": "error",
    "unicorn/prefer-modern-math-apis": "error",
    "unicorn/prefer-number-properties": "error",
    "unicorn/throw-new-error": "error",
  },
});
